FROM node:18-alpine as build-stage

WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
# Fix for ajv error in some environments
RUN npm install ajv ajv-keywords --legacy-peer-deps
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
